// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {news} from '../models';

export function GetArticles(arg1:string):Promise<Array<news.Article>>;
