// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetArticles(arg1) {
  return window['go']['news']['ArticleFetcher']['GetArticles'](arg1);
}
