// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {remote} from '../models';
import {server_repo} from '../models';
import {news} from '../models';
import {uuid} from '../models';

export function AddDevice(arg1:string,arg2:string,arg3:number,arg4:remote.Platform):Promise<void>;

export function AddServer(arg1:server_repo.Server):Promise<void>;

export function FetchImage(arg1:string):Promise<string>;

export function GetArticles():Promise<Array<news.Item>>;

export function GetDevice(arg1:string):Promise<remote.Device>;

export function GetDevices():Promise<{[key: uuid.UUID]: any}>;

export function GetSelectedDevice():Promise<remote.Device>;

export function GetSelectedServer():Promise<server_repo.Server>;

export function GetServer(arg1:string):Promise<server_repo.Server>;

export function GetServers():Promise<{[key: string]: server_repo.Server}>;

export function PatchDevice(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PatchFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectServer(arg1:string):Promise<void>;
