// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDevice(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddDevice'](arg1, arg2, arg3, arg4);
}

export function GetServer(arg1) {
  return window['go']['main']['App']['GetServer'](arg1);
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function PatchDevice(arg1, arg2) {
  return window['go']['main']['App']['PatchDevice'](arg1, arg2);
}

export function PatchFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['PatchFile'](arg1, arg2, arg3);
}
